NINT1 = 3 #4 neurônios internos + 1 bias
NINT2 = 10 #Assumirá NENT*aleartorio do outro módulo7
NINTER = 50 #Limite para pesos
NENT = 25 #2 neurônios de entrada + bias
NSAI = 1 #1 neurônio de saída
NPAD = 666 #Número de padrões do dataset completo
#Dataset = 80
TAPR = 0.5 #Taxa de aprendizagem
TAPR1 = 0.7
MAXITER = 650000 #Limite de iterações
ACEITAVEL = 0.0001 #Erro aceitável
err = 0.0 #Erro
emq = 0.0 #Erro médio quadrático
